### ISSUE TITLE
Canot build without libtirpc

### ISSUE THREAD

**Issue by ptsneves** [thkukuk/libnsl#17]
[configure.ac](https://github.com/thkukuk/libnsl/blob/74c9cdf0ee0cc1a21936a20dd4eb4542faa03867/configure.ac#L29) detects if libtirpc is available or not, implying that build would be possible without it. Is this the case, or it is just dead code from the fork?
I ask this because [ntirpc](https://github.com/nfs-ganesha/ntirpc/commit/e468dd3c8e96314ea36ca005dd8c4fdff2f3fd4d), a forked ti-rpc requires libnsl which in turn is also depending on ti-rpc.

**Comment by thkukuk** [comment]
libnsl needs either libtirpc or a RPC implementation as part of libc. When the configure script was written, all major libc implementations did include a RPC implementation, that's why the check for libc RPC support is missing.
So yes, you can build libnsl without libtirpc if your libc includes RPC support.

**Comment by thkukuk** [comment]
@zixubingfeng your questions has nothing to do with this issue. Please open separate issues for new problems.

1. Your `configure` is broken, `PKG_CHECK_MODULES` should never end in configure. Seems like you try to build from git instead of using the released tar archive. Please fix your build environment first.
2. According to your output Oracle requires libnsl.so.2, but this project only provides libnsl.so.3. So even if you get your build environment fixed and this project build, it will not solve your problem with Oracle.

Please use an Oracle certified distribution, that should provide all required dependencies in a compatible format.
